"""Bundle the offline results into docs/data.js for the article.

Most of the page needs nothing from here - the detector widgets re-run the
simulation live in the browser via docs/sharkhunt.js. Only the population fits
land here, because sampling a posterior is not something a page can do while you
read it.

    python -m sharkhunt.export --out docs/data.js
"""

import argparse
import json
import pathlib

SLIM_FIT_KEYS = [
    "prevalence", "prior_strength", "population_profile", "play_profile",
    "tank_profile", "profile_error", "auc", "n_players", "n_sharks",
    "matches", "seconds", "detector",
]


def read_json(path):
    p = pathlib.Path(path)
    if not p.exists():
        print(f"  ! missing {p}")
        return None
    return json.loads(p.read_text())


def trim_results(results):
    """The parts of the detector experiments the page actually plots."""
    if not results:
        return None
    keys = [
        "config", "evidence_table", "pinning_curve", "archetype_table",
        "calibration_by_betting_habit", "prior_strength_sweep",
        "economics_curve", "hidden_skill_sweep",
    ]
    out = {k: results[k] for k in keys if k in results}
    field = results.get("field_study")
    if field:
        out["field_study"] = {
            k: field[k] for k in
            ["n_players", "matches", "shark_fraction", "rates",
             "false_positives_by_archetype"] if k in field
        }
    return out


def trim_fits(fits):
    """Posterior means and the transfer curve. The raw draws stay out of the page."""
    if not fits:
        return None

    def slim(entry):
        return {k: entry[k] for k in SLIM_FIT_KEYS if k in entry}

    return {
        "grid": fits["grid"],
        "truth": fits["truth"],
        "game_a": {**slim(fits["game_a"]), "weights": fits["game_a"]["weights"]},
        "transfer": [
            {"n_players": r["n_players"], "matches": r["matches"],
             "n_sharks": r["n_sharks"], "cold": slim(r["cold"]), "warm": slim(r["warm"])}
            for r in fits["transfer"]
        ],
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", default="analysis/results.json")
    ap.add_argument("--fits", default="analysis/fits.json")
    ap.add_argument("--out", default="docs/data.js")
    args = ap.parse_args()

    print("collecting:")
    payload = {
        "detectors": trim_results(read_json(args.results)),
        "fits": trim_fits(read_json(args.fits)),
    }

    path = pathlib.Path(args.out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "/* Generated by sharkhunt/export.py - do not edit.\n"
        "   The only results the page cannot recompute for itself: posterior means\n"
        "   from the population fits. Every detector widget simulates live. */\n"
        "window.SHData = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    )
    print(f"wrote {path} ({path.stat().st_size / 1024:.0f} KB)")
    for key, value in payload.items():
        print(f"  {key:12} {'missing' if value in (None, []) else 'ok'}")


if __name__ == "__main__":
    main()
